com:
    tomcat:
        apr: true
        
server:
    port: 8761

spring:
    application:
        name: discovery
    cloud:
        client:
            hostname: localhost

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        enableSelfPreservation: false
        renewalPercentThreshold: 1
        waitTimeInMsWhenSyncEmpty: 3
    instance:
        leaseRenewalIntervalInSeconds: 3
    dashboard:
        enabled: false

management:
    security:
        enabled: false

endpoints:
    sensitive: false
    mappings:
        sensitive: false
   

http:
    mappers:
        json-pretty-print: true      
        
---

spring:
    profiles: discovery1
    
server:    
    port: 8761
    
eureka:
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8762/eureka/
        fetchRegistry: true    
    
---

spring:
    profiles: discovery2
    
server:    
    port: 8762
    
eureka:
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetchRegistry: true        